version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node --version
      - npm --version

  build:
    commands:
      - ./infra/codebuild/validate-frontend.sh pull-request

cache:
  paths:
    - /root/.npm/**/*
