import React, { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Loader2 } from "lucide-react";

export default function ShareViewer() {
  const [location] = useLocation();
  const token = React.useMemo(() => {
    const parts = location.split("/");
    return parts[2] || ""; // /share/:token
  }, [location]);

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [snapshot, setSnapshot] = useState<any>(null);

  useEffect(() => {
    let active = true;
    async function load() {
      try {
        const res = await fetch(`/api/dashboard/share/${token}`);
        if (!res.ok) throw new Error(`${res.status}: ${await res.text()}`);
        const data = await res.json();
        if (active) setSnapshot(data);
      } catch (e: any) {
        if (active) setError(e?.message || "Failed to load share");
      } finally {
        if (active) setLoading(false);
      }
    }
    if (token) load();
    return () => { active = false };
  }, [token]);

  if (loading) {
    return (
      <div className="container mx-auto max-w-3xl py-12 px-4 flex items-center justify-center">
        <Loader2 className="h-6 w-6 animate-spin" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="container mx-auto max-w-3xl py-12 px-4">
        <Alert variant="destructive">
          <AlertTitle>Unable to load shared dashboard</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      </div>
    );
  }

  return (
    <div className="container mx-auto max-w-5xl py-8 px-4">
      <Card>
        <CardHeader>
          <CardTitle>Shared Dashboard Snapshot</CardTitle>
          <CardDescription>Read-only view generated by the owner</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {snapshot?.summary ? (
            <pre className="text-sm whitespace-pre-wrap bg-muted p-4 rounded-md overflow-auto">{JSON.stringify(snapshot.summary, null, 2)}</pre>
          ) : (
            <div className="text-sm text-muted-foreground">No summary provided</div>
          )}
          {snapshot?.widgets && Array.isArray(snapshot.widgets) && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {snapshot.widgets.map((w: any, idx: number) => (
                <Card key={idx} className="border-dashed">
                  <CardHeader>
                    <CardTitle className="text-base">{w.title || `Widget ${idx+1}`}</CardTitle>
                    {w.description && (<CardDescription>{w.description}</CardDescription>)}
                  </CardHeader>
                  <CardContent>
                    <pre className="text-xs whitespace-pre-wrap bg-muted p-3 rounded-md overflow-auto">{JSON.stringify(w.data ?? w, null, 2)}</pre>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
          <div className="pt-2">
            <Button asChild variant="outline"><a href="/" >Back to Home</a></Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}


